author: António Costa
title: glitching.world
email: glitching.world@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A place to aim for the impossible while requiring huge amounts of coffee.
  Welcome to my little Blog / Portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://glitching-world.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: glitching_world
github_username: glitching-world

# Build settings
# theme: minima # removed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
